+++++++++++++++++++++
Debug a CPython crash
+++++++++++++++++++++

Core dump
=========

Write core dumps on the current directory::

    $ ulimit -c
    unlimited
    $ sudo bash -c 'echo "coredump-%e.%p" > /proc/sys/kernel/core_pattern'

Check that it works::

    $ ./python -c 'import _testcapi, signal; _testcapi.raise_signal(signal.SIGABRT)'
    Aborted (core dumped)
    $ ls coredump*
    coredump-python.23861

    $ gdb ./python -c coredump-python.23861
    GNU gdb (GDB) Fedora 8.0.1-36.fc27
    (...)
    Core was generated by `./python -c import _testcapi, signal; _testcapi.raise_signal(signal.SIGABRT)'.
    Program terminated with signal SIGABRT, Aborted.
    (gdb) where
    #0  0x00007fb0cb3ad050 in raise () from /lib64/libpthread.so.0
    #1  0x00007fb0c3a53006 in test_raise_signal (self=<module at remote 0x7fb0cb624758>,

Ok, Python crashes generate coredump files and gdb is able to load them.
